#!/usr/bin/env bash
# vim: ft=sh sw=2 et

set -euo pipefail

snack -j4 build -s code/snack.nix
snack -j4 run -s code/snack.nix | diff golden -

TMP_FILE=$(mktemp)

capture_io "$TMP_FILE" main | snack -j4 -s code/snack.nix ghci

diff golden $TMP_FILE
rm $TMP_FILE
