#!/usr/bin/env bash
# vim: ft=sh sw=2 et

set -euo pipefail

$SNACK build -f code/snack.nix
$SNACK run -f code/snack.nix | diff golden -

TMP_FILE=$(mktemp)

capture_io "$TMP_FILE" main | $SNACK -f code/snack.nix ghci

diff golden $TMP_FILE
rm $TMP_FILE
