#!/usr/bin/env bash
# vim: ft=sh sw=2 et

set -euo pipefail

snack build -f code/snack.nix
snack run -f code/snack.nix | diff golden -

TMP_FILE=$(mktemp)

capture_io "$TMP_FILE" main | snack -f code/snack.nix ghci

diff golden $TMP_FILE
rm $TMP_FILE
