#!/usr/bin/env bash
# vim: ft=sh sw=2 et

set -euo pipefail

test() {
  TMP_FILE=$(mktemp)

  capture_io "$TMP_FILE" main | $SNACK ghci -- -XOverloadedStrings

  diff golden $TMP_FILE
  rm $TMP_FILE
}

SNACK="snack --package-file ./package.nix" test
SNACK="snack --package-file ./package.yaml" test
