#!/usr/bin/env bash
# vim: ft=sh sw=2 et

set -euo pipefail

snack -j4 build
snack -j4 run | diff golden -

TMP_FILE=$(mktemp)

capture_io "$TMP_FILE" main | snack -j4 ghci

diff golden $TMP_FILE
rm $TMP_FILE
