#!/usr/bin/env bash
# vim: ft=sh sw=2 et

set -euo pipefail

TMP_DIR=$(mktemp -d)

git clone http://github.com/2mol/pboy.git $TMP_DIR
git -C $TMP_DIR reset --hard df5888f8e3b64566ebf0249ef7c11d05b9705356

snack -j4 build --package-yaml $TMP_DIR/package.yaml

rm -rf $TMP_DIR
