#!/usr/bin/env bash
# vim: ft=sh sw=2 et

set -euo pipefail

test() {
  echo | $SNACK ghci
  $SNACK run
}

SNACK="snack -j4" test
SNACK="snack -j4 -s ./package.nix" test
SNACK="snack -j4 -s ./package.nix -l ../../snack-lib" test
SNACK="snack -j4 --package-yaml ./package.yaml" test
