#!/usr/bin/env bash
# vim: ft=sh sw=2 et

set -euo pipefail

test() {
  echo | $SNACK ghci
  $SNACK run
}

SNACK="snack -j4 --package-file ./package.nix" test
SNACK="snack -j4 --package-file ./package.nix -l ../../snack-lib" test
SNACK="snack -j4 --package-file ./package.yaml" test
