#!/usr/bin/env bash
# vim: ft=sh sw=2 et

set -euo pipefail


test() {
  $SNACK build
  $SNACK run | diff golden -

  TMP_FILE=$(mktemp)

  capture_io "$TMP_FILE" main | $SNACK ghci

  diff golden $TMP_FILE
  rm $TMP_FILE
}

SNACK="snack -j4 --snack-nix snack.nix --package-file package.nix" test
SNACK="snack -j4 --snack-nix snack.nix --package-file package.yaml" test
