#!/usr/bin/env bash
# vim: ft=sh sw=2 et

set -euo pipefail

test() {
  $SNACK build
  $SNACK run | diff golden -

  TMP_FILE=$(mktemp)

  capture_io "$TMP_FILE" main | $SNACK ghci

  diff golden $TMP_FILE
  rm $TMP_FILE
}


SNACK="snack -j4" test

# TODO: Fix cannot coerce a list to a string, at /...-snack-lib/files.nix:66:12
SNACK="snack -j4 -s ./package.nix" test

# TODO: Fix cannot coerce a list to a string, at /...-snack-lib/hpack.nix:60:37
SNACK="snack -j4 --package-yaml ./package.yaml" test
