#!/usr/bin/env bash
# vim: ft=sh sw=2 et

set -euo pipefail

TMP_FILE=$(mktemp)

cat $(snack build) | jq -M 'keys' > $TMP_FILE

diff golden.jq $TMP_FILE

capture_io "$TMP_FILE" main | snack ghci
diff golden $TMP_FILE

rm $TMP_FILE
